### ISSUE TITLE
Cannot replay Gif animation from beginning

### ISSUE THREAD

**Issue by BrainCrumbz** [kirualex/SwiftyGif#101]
### Steps to reproduce

1. create `UIImage` with `UIImage(gifName:)` from a local GIF file bundled in project
1. create `UIImageView` and set GIF with `imageView.setGifImage(gifImage, manager: SwiftyGifManager.defaultManager, loopCount: 1)`
1. play GIF animation once with `imageView.startAnimatingGif()`
1. wait until animation completes
1. force playing GIF animation once again with:

```
imageView.showFrameAtIndex(0)
imageView.startAnimatingGif()
```

### Expected result

* GIF starts playing back again from first frame

### Actual result

* GIF moves back to first frame, but stays stopped

We also tried adding an `updateCurrentImage()` call, with no luck.

What are we doing wrong?

### Environment

* SwiftyGif version: 4.2.0
* Xcode: 10.1 (10B61)

**Comment by alexiscreuzot** [comment]
Could you try : 
```
        self.imageView.stopAnimatingGif()
        self.imageView.showFrameAtIndex(0)
        self.imageView.startAnimatingGif()
```

**Comment by BrainCrumbz** [comment]
Hi there! Thanks for your reply.

Probably we did that before already, but in any case we tried it now, in that same sequence, with no luck.  
Just for a test, we tried changing the index to something different than 0 and it does actually show a different frame, but animation does not start.

Is there anything we can do to debug or tracing down anything strange happening?

Thanks again for your time

### Edit
If that can help: we have two `UIImageView`s, each receiving their own `UIImage`. Each `UIImage` is created from the one same GIF file bundled in project. After playing animation once for __one__ of the `UImageView`, none of them is able to play animation anymore.

**Comment by alexiscreuzot** [comment]
I think this might be caused by both `UIImageView` trying to access the same data. Did you try using 2 different `SwiftyGifManager` instances?

**Comment by BrainCrumbz** [comment]
Each image view gets a new `SwiftyGifManager.defaultManager` through `setGifImage()` anyway. But we could also solve that by duplicating GIF files altogether. 

Apart from that, we're looking on how to solve the replay problem. That shows up even with just a single `UIImageView`/`UIImage`.

Would it be useful to have a sample project showing the issue? Or any other way we can try to track it down?

If it can help thinking, a workaround we're trying now is to create a new `UIImage` and re-assign that to the image view each time we want to replay. But, as said, it looks more like a workaround than a solution.

Another workaround, even simpler, is to repeat the same `setGifImage()` operation, which basically means to re-assign the same `UIImage` to the same `UIImageView`, but with a new manager:

```
// replay from beginning

imageView.stopAnimatingGif()

imageView.setGifImage(
    imageView.gifImage!, 
    manager: SwiftyGifManager.defaultManager, 
    loopCount: 1)

imageView.startAnimatingGif()
```

**Comment by alexiscreuzot** [comment]
`defaultManager` is a singleton, so you're not creating a new instance but using the same one over again. You should try creating a new instance of `SwiftyGifManager` throught its init function for each one.

**Comment by BrainCrumbz** [comment]
Hi there. Sorry for delayed feedback: just to let you know that even creating a brand new manager, behaviour is the same and problem persists.

Is there anything we can do to better expose the issue? Or to get to a *non-workaround* solution?

Thanks!

**Comment by alexiscreuzot** [comment]
using infinite looping with `loopCount = -1` isn't an option for you?

**Comment by BrainCrumbz** [comment]
No, we are experiencing this in a different use case:

1. given a view controller, create container image view once (in that view controller lifetime) and set Gif image on it. Gif has loopCount 1 
1. multiple times during view controller lifetime (e.g. everytime user taps somewhere):
   1. play animation (just one loop) from that same image view

The last point is where we have the issue. After the first time we play animation, the next time the image stays still, no animation played.

**Comment by hnguyen094** [comment]
I think I found the issue: loopCount gets pushed down to 0 when it gets done playing, so doing: 
```
    imageView.loopCount = 1  
    imageView.startAnimatingGif()
```
works for me.
