### ISSUE TITLE
When I do another giphy the cache is using the old giphy and not updating

### ISSUE THREAD

**Issue by Vadimkomis** [kirualex/SwiftyGif#102]
I tried:
`imageView.stopAnimatingGif()`
`SwiftyGifManager.defaultManager.deleteImageView(imageView)`

and it still does not work.

**Comment by alexiscreuzot** [comment]
Could you elaborate? Give a sample of your code for instance

**Comment by Vadimkomis** [comment]
Sure. 
here is where I animate the giphy:
  `lazy var giphyImageView:UIImageView = {
        SwiftyGifManager.defaultManager.haveCache = false
        SwiftyGifManager.defaultManager.clear()
        let giphyImageWidthAndHeight = FLLayoutConstants.defaultUIComponentSize
        let imageType = UIImageView(frame: CGRect(x: 24, y: FLLayoutConstants.contentPad, width: giphyImageWidthAndHeight, height: giphyImageWidthAndHeight))
        let gif = UIImage(gifName: giphyName)
        imageType.setGifImage(gif)
        imageType.loopCount = 1
        imageType.startAnimatingGif()
        return imageType
    }()`


And here's where I stop/dismiss the animation:
`func dismiss() {
        guard let snackBarWindow = snackBarWindow else {
            return
        }
        overlay.alpha = 1
        snackBarWindow.isHidden = true
        snackBarWindow.removeFromSuperview()
        snackBarWindow.rootViewController = nil
        self.snackBarWindow = nil
        for view in snackBarWindow.subviews{
            view.removeFromSuperview()
        }
        originalWindow?.makeKey()
        originalWindow = nil
        animating = false
        giphyImageView.stopAnimatingGif()
        giphyImageView.image = nil
    }`

**Comment by Vadimkomis** [comment]
I realized that this was not the cause of the issue. As a result, I'm closing this issue.

**Comment by juanjovn** [comment]
How did you solve the problem? @Vadimkomis
