### ISSUE TITLE
Gif appears only one time

### ISSUE THREAD

**Issue by minaMagedNaeem** [kirualex/SwiftyGif#103]
I use SwiftyGif to play a gif image using this code:
do {
            shoppieImage.setGifImage(try UIImage(gifName: "gif_coin_flip"), manager: gifManager, loopCount: -1)
        } catch let error {
            print(error)
        }

The above code worked perfectly until I updated SwiftyGif to v5.0.1
The gif appears correctly but when I dismiss the view controller and present it again the gif does not appear

**Comment by MrPovilas** [comment]
Similar problem here (also just with v.5.0.1). I play one gif at app launch, and after some actions play different gif, so the initial gif displayed normally, but second one is not displayed anymore.

**Comment by buh** [comment]
I fixed the issue in PR #104, check my [fork](https://github.com/buh/SwiftyGif).

**Comment by minaMagedNaeem** [comment]
Could you please tell me how to install the pod on this fork?

**Comment by buh** [comment]
@minaMagedNaeem 
```
pod 'SwiftyGif', :git => 'https://github.com/buh/SwiftyGif.git'
```

Please, let me know if my fork fixed your problem.

**Comment by minaMagedNaeem** [comment]
I get this exception:

dyld: lazy symbol binding failed: Symbol not found: _$sSf9SwiftyGifE7defaultSfvau
  Referenced from: /var/containers/Bundle/Application/A290A93A-B7F8-4F34-9746-7B16C25C97D2/ShopX.app/ShopX
  Expected in: /private/var/containers/Bundle/Application/A290A93A-B7F8-4F34-9746-7B16C25C97D2/ShopX.app/Frameworks/SwiftyGif.framework/SwiftyGif

dyld: Symbol not found: _$sSf9SwiftyGifE7defaultSfvau
  Referenced from: /var/containers/Bundle/Application/A290A93A-B7F8-4F34-9746-7B16C25C97D2/ShopX.app/ShopX
  Expected in: /private/var/containers/Bundle/Application/A290A93A-B7F8-4F34-9746-7B16C25C97D2/ShopX.app/Frameworks/SwiftyGif.framework/SwiftyGif

**Comment by buh** [comment]
Did you try to clean Xcode cache ⇧⌘K?

Another thing, that I changed a little by API to load gif by URL, it shouldn't be optional, but now it returns an URLSessionTask, where it could be cancelled.

**Comment by minaMagedNaeem** [comment]
Ok it worked out well but I'll test it, Should anything happen I will tell you asap.

**Comment by minaMagedNaeem** [comment]
I tried downloading it again and it shows me that it wants username and password

**Comment by alexiscreuzot** [comment]
that isn't something related to this library
