### ISSUE TITLE
Not able to load the gif

### ISSUE THREAD

**Issue by dishasyno** [kirualex/SwiftyGif#105]
I am using swift 5. I have outlet of my imageView and trying to load gif with loopCount but not able to load with "gifImgView = UIImageView(gifImage: UIImage(gifName: "Avo_Run.gif"), loopCount: 10)" . If i am loading the gif with "gifImgView.setGifImage(UIImage(gifName: "Avo_Run.gif"))" . then it is working fine but i want to set loop count for that. Kindly help

**Comment by buh** [comment]
Hey @dishasyno!
The method `setGifImage` has `loopCount` parameter and it should work.
Could you show me a little bit more code that doesn't work for you?

**Comment by dishasyno** [comment]
Hi @buh 
Not sure exactly what was the issue, but finally got it working fine.
Thank you
