### ISSUE TITLE
Pod is not taking the latest version

### ISSUE THREAD

**Issue by jfalexvijay** [kirualex/SwiftyGif#109]
Hi, today I was trying to use <code>SwiftyGif</code>. after pod installation command, I am getting some error saying <b>"The target “SwiftyGif” contains source code developed with Swift 2.x. This version of Xcode does not support building or migrating Swift 2.x targets."</b>

I found the below message from terminal

<code>"Installing SwiftyGif (4.2.0)" instead of 5.1.1</code>

Can you please help me to use latest version of <code>SwiftyGif</code>

**Comment by jfalexvijay** [comment]
Unable to specify the latest version in Podfile <code>pod 'SwiftyGif', '5.1.1'</code>

<code>
jfalexvijay$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "SwiftyGif":
  In Podfile:
    SwiftyGif (= 5.1.1)

None of your spec sources contain a spec satisfying the dependency: `SwiftyGif (= 5.1.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
jfalexvijay$
</code>

**Comment by alexiscreuzot** [comment]
Could you give me the version of cocoapods you use? `gem list | grep cocoapods`

**Comment by jfalexvijay** [comment]
below is the result:

jfalexvijay$ gem list | grep cocoapods
cocoapods (1.5.0)
cocoapods-core (1.5.0)
cocoapods-deintegrate (1.0.2)
cocoapods-downloader (1.2.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.3.0)
cocoapods-try (1.1.0)
jfalexvijay$

**Comment by alexiscreuzot** [comment]
Could you try with `1.6.0` ?

**Comment by jfalexvijay** [comment]
Hi Kirualex,

Sorry, I couldn't use the higher version.. because of some dependency software for my project.

Thank you for your support.
