### ISSUE TITLE
Support for Gif without no kCGImagePropertyGIFDictionary

### ISSUE THREAD

**Issue by billypchan** [kirualex/SwiftyGif#111]
Hi Alexis,
Thanks for this great library!
I have a suggestion for the case that the GIF has no `kCGImagePropertyGIFDictionary`, for example:
![not_animated](https://user-images.githubusercontent.com/11852044/58713295-8c2a7e80-83c2-11e9-99d1-81ce5f5815eb.gif)

When I load this image, I got an exception when calling `try UIImage(gifName: gifName)`. Here is my workaround to make it loaded as a normal `UIImage`:

```
extension UIImageView {
    func setGif(gifName: String, gifManager: SwiftyGifManager) throws {
        do {
            let gifImage = try UIImage(gifName: gifName)
            setGifImage(gifImage, manager: gifManager, loopCount: -1)
        } catch let error {
            print("Error : \(error.localizedDescription)")

            if let gifImage = UIImage(named: "\(gifName).gif") {
                image = gifImage
            } else {
                throw MyGifParseError.retryUIImageInitFail
            }
        }
    }
}

enum MyGifParseError: Error {
    case retryUIImageInitFail
}

```

**Comment by alexiscreuzot** [comment]
I guess this is fixed with your last pull request as I see `no_property_dictionary.gif` is displayed correctly. Closing
