### ISSUE TITLE
Swift Package Manager - Xcode 11 - Error

### ISSUE THREAD

**Issue by RobertEmoji** [kirualex/SwiftyGif#117]
Please add support for "Swift Package Manager" in Xcode 11. 

I can find kirualex/SwiftyGif in Swift Package Manager, but I'm unable to import it. I get this error message: 

```
The package dependency graph can not be resolved; unable find any available tag for the following requirements:

https://github.com/kirualex/SwiftyGif.git — 5.1.1
```

How to reproduce: 
Open a project in XCode 11.0 -> File -> Swift Packages -> Add Package Dependency -> search for "swiftygif"

**Comment by alexiscreuzot** [comment]
Swift Package Manager isn't supported yet

**Comment by simdani** [comment]
This one should work https://github.com/kirualex/SwiftyGif/pull/118 :)
