### ISSUE TITLE
Code with swift gif is crashing in ios13

### ISSUE THREAD

**Issue by drisharm** [kirualex/SwiftyGif#120]
I have to show a gif in iOS app launch. This is my piece of code, it is working fine in iOS 12, but app is crashing on launch in ios13.

let logoGifImageView: UIImageView = {
        guard let gifImage = try? UIImage(gifName: "abc.gif") else {
            return UIImageView()
        }
        return UIImageView(gifImage: gifImage, loopCount: 1)
    }()

In pod file, I have added SwiftGif like this:  pod 'SwiftyGif'

**Comment by alexiscreuzot** [comment]
This is too vague, please provide a crashlog
