### ISSUE TITLE
Add scale for gif images

### ISSUE THREAD

**Issue by monolithic-adam** [kirualex/SwiftyGif#122]
Add support for @1x, @2x, @3x scales for iPhone and iPad.
We have scales separated depending on use case and it would be great to not have to wrap the gifName init method myself.

**Comment by BrainCrumbz** [comment]
Hi @monolithic-adam 

is there any chance you could show us how are you "wrapping" the method at the moment? We just incurred in the same scenario, and were wondering what could be the cleanest technique to support it, apart from adding it into the library itself.

Thanks

**Comment by monolithic-adam** [comment]
Will do, I will try and put a gist up sometime this week/next week

**Comment by monolithic-adam** [comment]
> Hi @monolithic-adam
> 
> is there any chance you could show us how are you "wrapping" the method at the moment? We just incurred in the same scenario, and were wondering what could be the cleanest technique to support it, apart from adding it into the library itself.
> 
> Thanks

Sorry for the late response, rather than doing anything with swiftygif I added a simple extension to strings that adds the proper scale for each device size. There are probably better ways to do it but this is how I am doing it 🤷‍♂️

```swift
extension String {
    var scaled: String {
        let scale = UIScreen.main.scale
        return self + "@\(Int(scale))x"
    }
}
```

**Comment by alexiscreuzot** [comment]
This seems like a good solution
