### ISSUE TITLE
setImage(loopCount: 0) followed by showFrameAtIndex(lastIndex) loops forever

### ISSUE THREAD

**Issue by jruizcb** [kirualex/SwiftyGif#123]
I found a simple to reproduce logic bug in version 5.2.0

gifImage = try! UIImage(gifName: "animated.gif")
imageView.setGifImage(gifImage, loopCount: 0)
let index = isSelected ? gifImage.framesCount() - 2 : 0
imageView.showFrameAtIndex(index)

expected behavior: see last frame of image without animation
actual behavior: The displayed gif is animated continuously

**Comment by jruizcb** [comment]
I love this library though. Thanks for sharing.

**Comment by fazil1979** [comment]
I have also face same issue in my iOS app. The last indexed gif image from tableview plays continuously even If set loopCount:0.
Please let me know any solution for this, Otherwise I need to change whole implementation of this library in my App.

**Comment by alexiscreuzot** [comment]
DO you still have the issue with latest version ?
