### ISSUE TITLE
Error: invalidFileName

### ISSUE THREAD

**Issue by rafsannazmul** [kirualex/SwiftyGif#124]
Trying to load a gif file to start and stop animating it but every time showing invalidFileName error but my file name was similar to the gif file. I tried renaming the file couple of time but it is not accepting anything even though the name matches the ".gif file". Please help.

**Comment by alexiscreuzot** [comment]
make sure your file is in the main bundle

**Comment by Hannanparvez** [comment]
make sure your .gif is not in the xcassests but in the project folder.
