### ISSUE TITLE
gif images in table view cell with loading from url

### ISSUE THREAD

**Issue by askar1680** [kirualex/SwiftyGif#127]
in prepareForReuse if to clear image view, I can't set gif image after. if not to set, sometimes images start to repeat. (I combined gifs and images)

**Comment by Faari7** [comment]
I am also facing this issue and after spending hours on this issue, I commented on the code which I used by following this library and it starts working fine.  This library is great but this issue is killing the complete purpose of the library :)

**Comment by ad-1** [comment]
Same issue here using gifs in a collection view. Gif is slow to load firstly. Once it loads and the cell is reused the gif still appears even after setting to nil on dequeue. Makes it unusable for me unfortunately.

**Comment by alexiscreuzot** [comment]
Please use `clear()` method on the imageView

**Comment by Faari7** [comment]
> Please use `clear()` method on the imageView

when do we need to call that clear method?

**Comment by alexiscreuzot** [comment]
https://github.com/kirualex/SwiftyGif/blob/master/SwiftyGifExample/Cell.swift#L22-L25

**Comment by Faari7** [comment]
> https://github.com/kirualex/SwiftyGif/blob/master/SwiftyGifExample/Cell.swift#L22-L25

I just tried this solution but still, the issue is there.

**Comment by denis-obukhov** [comment]
Same issue. I do clear() on prepareForReuse and get empty image views for static images in my collection view while scrolling.
