### ISSUE TITLE
Getting sizes ?

### ISSUE THREAD

**Issue by petaire92** [kirualex/SwiftyGif#13]
Hey ! Thanks for your work.

I need to get the size from my UIImage, but it doesnt seems to work when I'm using UIImage(gifName:). I'm doing it on your demo project. In DetailController I've added one print line : 

```
        if let imgName = self.gifName {
            let gifImage = UIImage(gifName: imgName)
            self.imageView.setGifImage(gifImage, manager: gifManager, loopCount: -1)
            print(gifImage.size.height)
        }
```

I'm only getting 0... Do you have a way around ?

**Comment by alexiscreuzot** [comment]
one way could be to get the first frame with `frameAtIndex` function. Only on Swift3 branch for now though.
