### ISSUE TITLE
Remove Gif

### ISSUE THREAD

**Issue by hardiktgreydesk** [kirualex/SwiftyGif#130]
Hello,

After once we add gif , i need to remove if user click on none button how  can we remove that ?

**Comment by nikhilsingla11** [comment]
Hi,

I was facing the same issue with the library, i resolved it simply setting blank image.
yourImageView.setImage(UIImage()).

**Comment by vadubov** [comment]
> Hi,
> 
> I was facing the same issue with the library, i resolved it simply setting blank image.
> yourImageView.setImage(UIImage()).

Didn't work for me. I solved it this way
```
imageView.animationManager?.deleteImageView(imageView)
imageView.clear()
```
