### ISSUE TITLE
SwiftyGif crash, due to fast delay ?

### ISSUE THREAD

**Issue by Creanomy** [kirualex/SwiftyGif#134]
Hi, I used SwiftyGif to animate my logo that can not be animated with Lottie (too much complicated).
SwiftyGif do the job.
I present this logo at the launch of the app. As I can not avoid from looping, I used a timer func that remove the gif container and then performSegue to present a new screen.
For some reasons, after maybe 20 or 30 launchs, it makes crash my app on iPhone and will ever crash after it (i need to reinstall the app)... it never crashes in simulator, so I can not tell you about the logcrash...
I want my gif to be very fluent, so the speedrate is very high (delay = 0.02).
I don't see huge memory usage at launch, my gif is quite lightweight..
Do you think it could crash because of the delay ?

**Comment by alexiscreuzot** [comment]
This is not enough information to investigate. I"m not sure I understand the issue with the logs, it's perfectly possible (and even recommended) to have a log system on production apps. 
If you know this comes from the library, you must at least have a crash report, no?
Without some more info I'll have to close this issue

**Comment by Creanomy** [comment]
My question was simply irrelevant. As my SwiftyGif animation occured at the launch app, I thought that crashes happened because of SwiftyGif. No elements in my log system, no crashes during tests, impossible to verify.... until this :
https://stackoverflow.com/questions/38307356/iphone-app-under-test-crashes-after-a-few-days
Just a problem of validity with free developer account : 7 days of use before expiration...
Nothing else and I didn't know about this temporary validity. 
Sorry about this misunderstanding.
