### ISSUE TITLE
Xcode 12 throws warning

### ISSUE THREAD

**Issue by lalkrishna** [kirualex/SwiftyGif#140]
Xcode 12 throws warning:

`The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99.`

Version: 5.3.0
Dependancy manager: SPM
Xcode version: 12.1 (12A7403)

**Comment by edelabar** [comment]
It looks like this has been fixed in the master branch, just needs a new version tag, anything holding it back?
