### ISSUE TITLE
Always crash in UIImageView+SwiftyGif line 436 ;  iPhone 7 -12.2 

### ISSUE THREAD

**Issue by muyuli** [kirualex/SwiftyGif#143]
crash 
get { return (objc_getAssociatedObject(self, _delegateKey!) as? SwiftyGifDelegate) }

**Comment by MuYuLi** [comment]
@kirualex hello,  Do you know the reason ? please

**Comment by muyuli** [comment]
Looking forward to your reply hhhhh @kirualex
