### ISSUE TITLE
byte too large

### ISSUE THREAD

**Issue by sjustfly** [kirualex/SwiftyGif#146]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/3159210/100995958-77b8da80-3593-11eb-91f2-184e96c08bf0.png">
this library too big, download is hard. please remove the large picture.

**Comment by alexiscreuzot** [comment]
I've tried to remove some files with bug but I'm not an expert with this tool, do have a look if it's better

**Comment by alexiscreuzot** [comment]
Yes it seems it's now around 150MB
