### ISSUE TITLE
Memory Issue on Keyboard

### ISSUE THREAD

**Issue by vittorionapoli** [kirualex/SwiftyGif#157]
Hi,
first of all thanks for creating this repository, It works very well and save so much time!!!

I'm trying to use it inside a collection view of a keyboard extension but after some scrolls the keyboard crash for out of memory issue.

I use a SwiftyGifManager with a limit of 10mb (so the keyboard doesn't have to crash if the manager keeps the use of memory inside this range) and also 0.5 of levelOfIntegrity.

Where can be the problem?

Thanks,
Vittorio

**Comment by alexiscreuzot** [comment]
DO you still have the issue with latest version ?
