### ISSUE TITLE
Issue on loading a png image after loading a gif image in same image view. 

### ISSUE THREAD

**Issue by Minna** [kirualex/SwiftyGif#173]
First I loaded a png image in my image view in my cell. then I loaded a gif file from server after that I tried to load same png. but it is showing the previous Gif image.

**Comment by karlmcgeough** [comment]
Also having this issue in a tableview cell... when I switch to show png and not the gif it still displays the previous gifs

**Comment by yousaf94** [comment]
Anyone found solution to this ?

**Comment by alexiscreuzot** [comment]
did you try setting the gif to `nil` before setting the png ?
