### ISSUE TITLE
Load gif from app local cache

### ISSUE THREAD

**Issue by Pixette** [kirualex/SwiftyGif#177]
Hello

I tried several method (dataGif, setGifFromURL) but I cannot achieve this basic use case:

All my gif are located in the app local cache, example of URL: file:///Users/Test/Library/Developer/CoreSimulator/Devices/73604AB6-EB54-4CDD-AE82-88773A68883A/data/Containers/Data/Application/C58B5674-0986-41AD-B331-3957B9C45226/Library/Caches/MyGid/-4571298005762920152-6951373780214.gif

How to load them into an imageView ?

Thank you very much

**Comment by alexiscreuzot** [comment]
This should work out of the box actually, have you try putting that data in memory before using it and checking the size ?
