### ISSUE TITLE
$sSo7UIImageC9SwiftyGifE19calculateFrameDelay33_9658D83D62B37A941BEC0DE7CE976670LL_16levelOfIntegrityySaySfG_SftF

### ISSUE THREAD

**Issue by ygg-minna** [kirualex/SwiftyGif#189]
We are getting crash when loading gif in collection view. 

[issue_738711ca2cdf94375b7a5cc6aeff47b2_crash_session_08b82e77c33f4416881241a4c7aee045_DNE_0_v2_stacktrace.txt](https://github.com/kirualex/SwiftyGif/files/11609195/issue_738711ca2cdf94375b7a5cc6aeff47b2_crash_session_08b82e77c33f4416881241a4c7aee045_DNE_0_v2_stacktrace.txt)

**Comment by alexiscreuzot** [comment]
Can you try with 3cbe364601288106d57f452b0ff5a4215392a689 ?
