### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DamonChen117** [kirualex/SwiftyGif#19]
crash at           return (objc_getAssociatedObject(self, _imageCountKey) as! Int)

as  (objc_getAssociatedObject(self, _imageCountKey) is nil

**Comment by alexiscreuzot** [comment]
Please do provide a way to reproduce the issue

**Comment by DamonChen117** [comment]
I have forgot how to reproduce it, but it is always dangerous to use code such as "as!".

**Comment by alexiscreuzot** [comment]
Ok that's more of a general advice, closing
