### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by infinitepower18** [kirualex/SwiftyGif#192]
Any plans to add a privacy manifest? Apple has explicitly mentioned SwiftyGif as one of the third party SDKs that must include a privacy manifest.

https://developer.apple.com/support/third-party-SDK-requirements

**Comment by neobeppe** [comment]
Please check out this PR: https://github.com/kirualex/SwiftyGif/pull/193

**Comment by alexiscreuzot** [comment]
closed with PR #193

**Comment by debadaracco** [comment]
Hi @kirualex 

Sorry by the comment but do you know when we will have a new release that includes this pull request? 

Thanks.
