### ISSUE TITLE
Support App Privacy Manifests

### ISSUE THREAD

**Issue by imk1t** [kirualex/SwiftyGif#195]
## Issue Description
SwiftyGif was listed on the list of requirements for third-party SDKs announced by Apple.
Is there any push on SwiftyGif part to include Privacy Manifests files or sign the SDK?
https://developer.apple.com/support/third-party-SDK-requirements/

### What

If this is not addressed, apps containing SwiftyGif will not be able to be submitted to the AppStore beginning in the spring of 2024.

**Comment by percival888** [comment]
PrivacyInfo.xcprivacy was already included in the SDK, but it was not exposed.

I submitted a PR #196 to fix this issue

**Comment by alexiscreuzot** [comment]
Merged

**Comment by BaroneX** [comment]
The podspec version needs to be updated.
There is no PrivacyInfo.xcprivacy file in version 5.4.4.

**Comment by LikeeCat** [comment]
> Merged
although  pr merged , but cocoapods spec repo not receive the new version ,so we can't use the PrivacyInfo.xcprivacy , may be we should release a new version or update the 5.4.4 podspec and push to the cocoapods
