### ISSUE TITLE
Gif from URL

### ISSUE THREAD

**Issue by alexwasner** [kirualex/SwiftyGif#2]
What is the correct way to load a gif from a URL? Currently, I am trying to use it with AlamoFire like this 

```
Alamofire.request(.GET, urlString).response { (request, response, data, error) in
       if let gif = UIImage(data: data!, scale:1){
            let gifManager = SwiftyGifManager(memoryLimit:20)
            self.imageView?.setGifImage(gif, manager: gifManager)
       }
}
```

but receive an optional unwrap fatal error in setGifImage

**Comment by alexiscreuzot** [comment]
I'll make some tests on this

**Comment by ben73** [comment]
@alexwasner `if let gif = UIImage(data: data!, scale:1){`
You should use UIImage(gifData: data!) instead UIImage(data: data!, scale: 1)
