### ISSUE TITLE
Need to update swift-tools-version 

### ISSUE THREAD

**Issue by devMinseok** [kirualex/SwiftyGif#204]
I tried to use SPM to use version 5.4.5 but I am getting the following error.
`'target(name:dependencies:path:exclude:sources:resources:publicHeadersPath:cSettings:cxxSettings:swiftSettings:linkerSettings:)' was introduced in PackageDescription 5.3`

I think swift-tools-version must be at least version 5.3 or later 🙏

**Comment by alexiscreuzot** [comment]
Done
