### ISSUE TITLE
gif freeze on iPad mini iOS 9.3.5

### ISSUE THREAD

**Issue by JeromeTW** [kirualex/SwiftyGif#21]
I got a wired problem.

`let gif = UIImage(gifName: INspeaker_loading_2x)`
`gifImageView.setGifImage(gif)`
`gifImageView.startAnimating()`

they are working well on my iPhone 6s (iOS 10.1.1),but on my iPad mini (iOS 9.3.5) the gifImageView will not play, and stay at first frame.

type "po gifImageView.isAnimating" get false in lldb.

install SwiftyGif by cocoapod with following version
SwiftyGif (3.0.0)
all code work on xcode 8.1 with swift 3.

Any help is appricated, thanks.

**Comment by alexiscreuzot** [comment]
I don't have an iPad mini here to check :\
