### ISSUE TITLE
Gif Not Animating when created using storyboard

### ISSUE THREAD

**Issue by Jerland2** [kirualex/SwiftyGif#22]
First I would like to say that everything is working as intended without storyboards, however when I tried to create an image view via storyboards the gif would just display as a still image using the following:

```
let gifManager = SwiftyGifManager(memoryLimit:20)
let gif = UIImage(gifName: "MyImage.gif")
self.myImageView.setGifImage(gif, manager: gifManager) 
```

Using Xcode 8.2.1
Swift 3

Edit: I would also for completeness like to add that i tried the following as well
`self.myImageView.setGifImage(gif, manager: gifManager, loopCount:-1)`

As I have said I have gotten my project to work without storyboards so I would just like to make sure this problem is known so that it can be fixed for others.

**Comment by alexiscreuzot** [comment]
Could you provide an example of a gif which displays this issue?

**Comment by alexiscreuzot** [comment]
Current sample works with a storyboard, so I'm not sure where to go from here. Could you provide the gif causing the issue?
