### ISSUE TITLE
To high memory usage !

### ISSUE THREAD

**Issue by medinpiranej** [kirualex/SwiftyGif#26]
Ram usage is very high when i use good quality Gifs.
Using this attached gif as progress once the ram usage is about 100mb !
![preloader](https://cloud.githubusercontent.com/assets/10618606/22396630/62e6e8a6-e55e-11e6-8df9-f8d0c55c4e80.gif)

**Comment by alexiscreuzot** [comment]
I managed to get it to run at a 30Mo memory use. I thing the dimension may be one of the reason. You may want to get a gif cropped to the actual animation.
![capture d ecran 2017-08-18 a 20 46 32](https://user-images.githubusercontent.com/431974/29473014-5a260818-8456-11e7-8993-a737bede4381.jpg)
