### ISSUE TITLE
ViewController doesn't deallocate on conforming to SwiftyGIFDelegate

### ISSUE THREAD

**Issue by zarif-ahmed** [kirualex/SwiftyGif#27]
I wanted to trigger a event when a GIF plays completely and starts the next loop. Thus i conformed my view controller to the `SwiftyGifDelegate` and implemented the `gifDidLoop()` method.

However, My view controller doesn't deallocate after this.

**Comment by neobeppe** [comment]
fixed in 3.0.2, thank you @zarif-ahmed
