### ISSUE TITLE
Crash: fatal error: Can't form Range with upperBound < lowerBound

### ISSUE THREAD

**Issue by IsaiahJTurner** [kirualex/SwiftyGif#29]
The breakpoint hits in `UIImage+SwiftyGif.swift` and the app crashes with the message `Crash: fatal error: Can't form Range with upperBound < lowerBound`

I am trying to play a gif with 100 loops and memory limit 20. I've also included the gif file that caused the issue. It seems to be reproducable.
![image](https://cloud.githubusercontent.com/assets/3732588/23592800/1b23fc60-01d4-11e7-85b7-dea1b0413295.gif)

```swift
//caclulate the time when each frame should be displayed at(start at 0)
for i in 1..<delays.count{ delays[i] += delays[i-1] }
```

**Comment by nishanth-saka** [comment]
Same Problem; please help! Thank you..

**Comment by IsaiahJTurner** [comment]
This seems to happen when the Gif is invalid. Such as trying to create a Gif from this text:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>messages-data/11387/image.gif</Key><RequestId>C3DDF27CDDDDD4DD</RequestId><HostId>SDFjh/jfasd89UHFSDNlas89fdhsduIOUAEHF/sdfhiwerjD/FhjH+JJsdfJLKfdsfnkJHEkjdsfNKJw=</HostId></Error>
```

**Comment by EdenShapiro** [comment]
I get the same issue when using a protobuf compiler. Any answers to this?

**Comment by alexiscreuzot** [comment]
Couldn't reproduce this issue on current version

**Comment by agustindc-rga** [comment]
I am running into the same issue if the data that is passed to `init(gifData:Data)` is not a valid gif.

```
let s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>messages-data/11387/image.gif</Key><RequestId>C3DDF27CDDDDD4DD</RequestId><HostId>SDFjh/jfasd89UHFSDNlas89fdhsduIOUAEHF/sdfhiwerjD/FhjH+JJsdfJLKfdsfnkJHEkjdsfNKJw=</HostId></Error>"

if let data = s.data(using: .utf8)  {
    let gifImage = UIImage(gifData: data)
```
