### ISSUE TITLE
Crash on SwiftyGifManager function deleteImageView

### ISSUE THREAD

**Issue by natanrolnik** [kirualex/SwiftyGif#3]
Here is the following crash report:
![captura de tela 2016-06-22 as 14 28 35](https://cloud.githubusercontent.com/assets/1164565/16265025/b2c9496c-3885-11e6-8400-c8fe790d7a80.png)

I'm only calling `myImageView.setGifImage(...)` from two places, and both are from the main thread. Any idea why this might be happening? Could it be some race condition?
It's very weird that the line pointed by the crash report is `self.totalGifSize -= imageView.gifImage!.imageSize!` and that the "reason" is `specialized specialized Array.replaceRange<A where ...> (Range<Int>, with : A1) -> (`

Thank you for this amazing project!

**Comment by alexiscreuzot** [comment]
I think it may be a race condition, maybe switching those 2 lines could do the trick : https://github.com/kirualex/SwiftyGif/blob/master/SwiftyGif/SwiftyGifManager.swift#L60-L61

**Comment by natanrolnik** [comment]
Thanks for the reply, @kirualex 
- But do you have any idea on how exactly the race condition happens? What is the reason that the `-=` operation fails? Who can be changing `displayViews` simultaneously?
- Is there any other safer way to fix it instead of just switching the lines?

**Comment by alexiscreuzot** [comment]
I've merged your fix. This will still need some study on that double `deleteImageView` call though. To be continued.
