### ISSUE TITLE
Gif animates very fast

### ISSUE THREAD

**Issue by atulvuliv** [kirualex/SwiftyGif#30]
I tried this recently in my project and saw that the gif was animating faster than it should. I cross checked in my browser and it was indeed the case.
Any idea why the speed is so fast?

I am using Swift3 with XCode 8.2

**Comment by kinshukkashyap** [comment]
you must be using the .setGifImage(image, manager, loopCount) function which takes a GiManager parameter. Declare this gifManager as a global class var not a local var inside the scope of the function.  See if that helps

**Comment by leojkwan** [comment]
hey @Faari7  @kirualex , Ran into same issue dequeuing table view cells. Followed your instructions to clear on `prepareForReuse` but still some cells are showing wrong images from other cells
