### ISSUE TITLE
Gif will not play when the ImageView is positioned on the right side of the view

### ISSUE THREAD

**Issue by Jovial-Xenchain** [kirualex/SwiftyGif#34]
Dear Developers,

I'm currently having issues where the Gif will not play if the ImageView is positioned on X above 200 with 75 Width and Height. Additionally when I check its isAnimatingGif() value, it shows as true even though the Gif is not playing at all. I know it sounds weird, but I cannot find other explanation which can cause this behaviour.

Thank you.

Best Regards,

Jovial

**Comment by thewthew** [comment]
I have the same problem. Have you found a solution?

**Comment by JBKaloya** [comment]
I have the same problem, the image is showing but not animated when its position is below half of the screen height :(
