### ISSUE TITLE
Suggest: Slow motion

### ISSUE THREAD

**Issue by gbergamo** [kirualex/SwiftyGif#42]
I'm using SwiftyGif to insert a gif like a uiview background. The library works perfect, but I suggest to create a function do control the speed of the gif. it will be perfect!

Thanks

**Comment by tiwariammit** [comment]
@kirualex  how can you closed both the issues, mine and @gbergamo  comment?

**Comment by tiwari1amrit** [comment]
@kirualex  Can you please make it?

**Comment by tiwariammit** [comment]
@kirualex issue is stilled not solved and how can you close my issue comment?

**Comment by tiwari1amrit** [comment]
@kirualex  I didn't see any solution for that issue, so had commented on that and it is stilled not solved and how can you closed my issue comment?

**Comment by alexiscreuzot** [comment]
It's not in the scope of that project, as we already fiddle with gif framerate to allow proper cpu/memory management.
