### ISSUE TITLE
Delegate gifDidStop not called

### ISSUE THREAD

**Issue by lucio1392** [kirualex/SwiftyGif#43]
I try to using delegate for imageView but only gifDidStop method delegate not called. Below is my code.

> func createSplashGif() {
    let gifImage = UIImage(gifName: "myVid_Splash")
    let gifMyvid = SwiftyGifManager(memoryLimit:20)
    self.splashImageView.delegate = self
    self.splashImageView.setGifImage(gifImage, manager: gifMyvid, loopCount: 1)
  }

> extension MVSplashViewController: SwiftyGifDelegate {
  func gifDidStop() {
    print("Did Stop") // Not calling
  }
}

Thanks.

**Comment by alexiscreuzot** [comment]
Watch out, new version is now passing a pointer to the sender likeso : 
```@objc public protocol SwiftyGifDelegate {
    @objc optional func gifDidStart(sender: UIImageView)
    @objc optional func gifDidLoop(sender: UIImageView)
    @objc optional func gifDidStop(sender: UIImageView)
}
```

**Comment by lucio1392** [comment]
Where is new version ?

I have pod a lastest version and still see the old delegate like below:

@objc public protocol SwiftyGifDelegate {
    @objc optional func gifDidStart()
    @objc optional func gifDidLoop()
    @objc optional func gifDidStop()
}

**Comment by lucio1392** [comment]
I have checked new source code from master and see the change. I think you should update pod too. Thanks.

**Comment by lucio1392** [comment]
Still not working

**Comment by AYASHI** [comment]
Same issue here, gifDidStop didn't called

**Comment by alexiscreuzot** [comment]
fixed on last release
