### ISSUE TITLE
Unable to find GIF despite placed in project folder. 

### ISSUE THREAD

**Issue by zallanx** [kirualex/SwiftyGif#47]
I am getting the error "Error : Gif file gif1.gif not found". However, `gif1.gif` is placed directly insider the project folder (see screenshot)

![image](https://user-images.githubusercontent.com/1867934/29148192-e62b2722-7d39-11e7-8228-f0c670f15b18.png)

This is the code I am using in `viewDidLoad`:

        self.gifManager = SwiftyGifManager(memoryLimit: 20)
        let gif = UIImage(gifName: "gif1")
        let imageview = UIImageView(gifImage: gif, manager: gifManager)
        imageview.frame = CGRect(x: 0.0, y: 5.0, width: 400.0, height: 200.0)
        view.addSubview(imageview)

What am I doing incorrectly in my set up?

I am using XCode 8.3.3

**Comment by alexiscreuzot** [comment]
Are you sure your image is correctly added to your target?
