### ISSUE TITLE
Index of Current Frame

### ISSUE THREAD

**Issue by zachcoss** [kirualex/SwiftyGif#5]
Is there a way to retrieve the index of the current image? 

Examples: 
The current image (UIImage: 000x02939) is 4 of 21.
Or gif.currentimage.index
or gif[currentimage.index]

**Comment by alexiscreuzot** [comment]
Done with : 
02857814 #8 add delegate to imageview

2 new functions : 

``` swift
public func currentFrameIndex() -> Int
public func frameAtIndex(index: Int) -> UIImage
```

On the Swift3 branch for now
