### ISSUE TITLE
Delegate doesn't get called 

### ISSUE THREAD

**Issue by ursanotsomajor** [kirualex/SwiftyGif#54]
Hello! Recently I updated to Xcode 9 and converted code to Swift 4. After that, method gifDidLoop stopped getting called.

**Comment by Softminilab** [comment]
@ursanotsomajor @kirualex I meet same issue, Have you solved the problem？

**Comment by ursanotsomajor** [comment]
@karepbq Nope, nothing worked out for me. Still waiting for the answer.

**Comment by Softminilab** [comment]
@ursanotsomajor Thanks！

**Comment by alexiscreuzot** [comment]
Could you try that with the swift4 branch?

**Comment by ariobarxan** [comment]
Hey, I'm using SwiftUI and ios 15.2 and swift 5.1, I'm experiencing the same issue, delegate functions won't work.
I used UIViewrepresentable and set all the parameters correctly.
