### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by oleghnidets** [kirualex/SwiftyGif#55]
Hi there,

As you know it is time for Swift 4 . I saw the branch you were working on.
Is it possible to release Swift 4 version asap? Do you need any help?

**Comment by VBUZZE** [comment]
We would also need a Swift 4 version asap please. We can't update our app because there is no Swift 4 version of SwiftyGif available yet. Thanks in advance & congratulation for your good work with this framework

**Comment by alexiscreuzot** [comment]
There is already a swift4 branch you can indicate in your Podfile (check the cocoapods documentation for more information)
