### ISSUE TITLE
Cannot build pod with new Swift compiler (new build system)

### ISSUE THREAD

**Issue by JohanDufau** [kirualex/SwiftyGif#57]
Hello,

When we use this pod (swift4 branch) in a project that is built with the new Swift compiler (in Xcode, in the File menu -> Project/Workspace settings -> select New build system), there is a issue when building:

```
unable to build node: '.../SwiftyGif/SwiftyGif.framework/Info.plist' (node is produced by multiple commands; e.g., '.../SwiftyGif/SwiftyGif.framework/Info.plist .../SwiftyGif/SwiftyGif/Info.plist' and '.../SwiftyGif/SwiftyGif.framework/Info.plist .../SwiftyGif/Info.plist')
```

This is due to an extra plist file present in the project.

This should be simply fixed being more specific in the podspec for source files declarations. For instance:
```
s.source_files = 'SwiftyGif/*{.h, .swift}'
```

Thanks!

**Comment by Imputes** [comment]
Can not import in Xcode 9.1 , Swift 4.0.2

**Comment by jigs611989** [comment]
Same issue...
Try change swift language version to 3.2 in Xcode 9.1, select pod project then select SwiftGif and change swift version only for this lib
<img width="1008" alt="screen shot 2017-11-03 at 11 23 01 pm" src="https://user-images.githubusercontent.com/12206811/32388574-28e2dc98-c0ee-11e7-83d2-29c7d8f2ee5c.png">

**Comment by Imputes** [comment]
I had changed before, but no use. I delete the pod, and drag those .swift files into my project, then everything is OK.

**Comment by alexiscreuzot** [comment]
Should be ok with last commits
