### ISSUE TITLE
CPU usage spikes when app enters background and then opens again

### ISSUE THREAD

**Issue by dlush315** [kirualex/SwiftyGif#6]
As the title says, if you press the home button to close the app and then reopen it, the CPU % spikes by a lot. Even the demo project does this. Not sure where the issue originates but would love to know if there's a way to fix it!!

**Comment by alexiscreuzot** [comment]
I can confirm the bug, I'll try to see where it could come from, it seems to be a tedious one

**Comment by dlush315** [comment]
Great, looking forward to hearing from you!

**Comment by dlush315** [comment]
Hey just wondering, any luck?

**Comment by alexiscreuzot** [comment]
nope! Not much time right now to dig deep into this sadly :/

**Comment by dlush315** [comment]
Ahh alright. I'm in the final stages of my app but I need a working gif engine. Love yours so I hope you can find a fix in the near future! Cheers.

**Comment by sewerynplazuk** [comment]
When app goes background both memory and CPU usage goes low (in my case: 30MB -> 12MB and 10% -> 0%). Normal behaviour. But when you reopen it - things goes interesting. Memory usage stay low (in my case 14MB), CPU goes up to 30-40%. I don't know if it is somehow related to this bug but it might be a clue.

**Comment by alexiscreuzot** [comment]
I've been looking into this but this is a tricky one.

**Comment by alexiscreuzot** [comment]
Tested extensively on last version of `master`, could not reproduce this issue
