### ISSUE TITLE
Pod Latest project giving compilation errors for unwrapping optional

### ISSUE THREAD

**Issue by irfangul10pearls** [kirualex/SwiftyGif#66]
Please check attached image, I tried latest version of pod with xcode 9.2 swift 4

![screen shot 2018-01-30 at 3 55 45 pm](https://user-images.githubusercontent.com/7964039/35562728-1e777a0c-05d6-11e8-9fbf-689c4e57c693.png)

**Comment by alexiscreuzot** [comment]
looks like we've got an improper swift version in the pod, I'm surprised this went through unnoticed, don't hesitate to make a PR, else I'll have it done ASAP

**Comment by irfangul10pearls** [comment]
updated my pod repo ..

**Comment by alexiscreuzot** [comment]
Alright! Just did a `pod try SwiftyGif` and I was wondering ^^ Closing time!
