### ISSUE TITLE
Need help on crash

### ISSUE THREAD

**Issue by raviteja11b** [kirualex/SwiftyGif#68]
Hi,
I am using this library in one project, and I love it
But due to some reasons, it's crashing occasionally, there is no proper way to reproduce it.
I have attached some screenshots of a crash report, please someone help me on this
Thanks for your help
![screen shot 2018-03-08 at 12 37 04 pm](https://user-images.githubusercontent.com/13586484/37137873-c93dae5c-22cd-11e8-84ee-ae079c61cfe6.png)
![screen shot 2018-03-08 at 12 36 30 pm](https://user-images.githubusercontent.com/13586484/37137893-db7dfd1a-22cd-11e8-9040-ea622ad157ee.png)

**Comment by alessandro-martin** [comment]
`OBJC_ASSOCIATION_ASSIGN` is equivalent to Objective-C's `unsafe_unretained` which means that it doesn't nil out the pointer on deallocation; you should use `OBJC_ASSOCIATION_RETAIN_NONATOMIC`.

**Comment by alexiscreuzot** [comment]
I changed those on the main branch, have a try at it!
