### ISSUE TITLE
How to unset GIF?

### ISSUE THREAD

**Issue by dimacorp** [kirualex/SwiftyGif#75]
When used in reusable cells (for example in UICollectionView) we need a method to unset the previous GIF before new one is loaded and displayed. Somehow stopAnimatingGif does not help - the old frame still blinks/freezes sometimes.

**Comment by dafurman** [comment]
We had a similar issue when using Gifs in collection view cells, and found a solution from this pull request: https://github.com/kirualex/SwiftyGif/pull/61#issue-154499802

Place the following in your prepareForReuse() function, or wherever you may be dequeuing a cell for reuse.
> imageView.stopAnimatingGif()
> SwiftyGifManager.defaultManager.deleteImageView(imageView)

**Comment by alexiscreuzot** [comment]
Thanks for helping @dafurman!
