### ISSUE TITLE
How to size the frame?

### ISSUE THREAD

**Issue by pandapancake** [kirualex/SwiftyGif#76]
Hi, I'm having problem for the frame size. I don't know how to set it.

This is from the simulator
![screen shot 2018-09-02 at 9 43 59 pm](https://user-images.githubusercontent.com/32947517/44963548-528f1a80-aef9-11e8-9087-d705eacdaa3e.png)

This is the original size
![screen shot 2018-09-02 at 9 43 55 pm](https://user-images.githubusercontent.com/32947517/44963564-69357180-aef9-11e8-87d9-5fdbb6f5ca14.png)

`import UIKit
import SwiftyGif

class SplashScreenVC: UIViewController {

    @IBOutlet weak var splashImageView: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let gif = UIImage(gifName: "coin.gif")
        let imageview = UIImageView(gifImage: gif, loopCount: 3) // Use -1 for infinite loop
        imageview.frame = view.bounds
        view.addSubview(imageview)
    }
} `

Thank you!

**Comment by alexiscreuzot** [comment]
You should apply the proper ratio of your UIImageView as a constraint.

**Comment by pandapancake** [comment]
Thanks!! I would like to know if SwiftyGif can support the activityIndicator? I tried to do it as http://www.tothenew.com/blog/create-custom-loader-using-images-in-ios-app/ but it didn't work. All the ways I found is using static images instead of actual gif file. 

`class CoinListVC: UIViewController, UITableViewDataSource, UITableViewDelegate {
   
    @IBOutlet weak var CoinListsTableVIew: UITableView!
    
    var activityIndicator : UIActivityIndicatorView?
    var coinArray: [Coin] = []

    override func viewDidLoad() {
        super.viewDidLoad()
        CoinListsTableVIew.delegate = self
        CoinListsTableVIew.dataSource = self
        
        configureActivityIndicator()
        coinFinder()
    }
    
    func configureActivityIndicator(){
//     activityIndicator = UIActivityIndicatorView(activityIndicatorStyle: .gray)     
//     (default style but i want to use the custom gif instead)

        let gif = UIImage(gifName: "CoinLoading.gif")
        let imageview = UIImageView(gifImage: gif, loopCount: -1) // Use -1 for infinite loop
        imageview.frame = CGRect(x: 0 , y: self.view.frame.height / 2, width: 200, height: 200)
   
        CoinListsTableVIew.tableFooterView = UIView(frame: .zero)
        activityIndicator?.hidesWhenStopped = true
        activityIndicator?.center = CoinListsTableVIew.center
        CoinListsTableVIew.addSubview(imageview)
    }
  
    func coinFinder() {
        activityIndicator?.startAnimating()

        DispatchQueue.global(qos: .background).async {
            // Heavy processing here.
            
            CoinListService.sharedInstance.getList{ (responseString, coinArray) in
                if (responseString == "error"){/* popup here alerting user about error*/ }
                else {
                    self.coinArray = coinArray
                    print("Success")
                }
                
                DispatchQueue.main.async {
                    self.activityIndicator?.stopAnimating()
                    self.CoinListsTableVIew.reloadWithAnimation()
                }
            }
        }`

When I ran the code the gif is showing but it only loop once and stops. After the tableView is load it will do the infinite loop and won't stop animating. :(   Thank you in advance!!

**Comment by rami965** [comment]
Here is much simpler solution that respects `conentMode` 

```swift
import SwiftUI
import SwiftyGif

struct AnimatedGifView: UIViewRepresentable {
    @Binding var url: URL
    
    var contentMode: UIView.ContentMode = .scaleAspectFill
    
    func makeUIView(context: Context) -> GifViewRepresentable {
        let view = GifViewRepresentable()
        view.imageView.contentMode = contentMode
        return view
    }
    
    func updateUIView(_ uiView: GifViewRepresentable, context: Context) {
        uiView.imageView.setGifFromURL(self.url)
        uiView.imageView.contentMode = contentMode // In case it changes dynamically
    }
}

final class GifViewRepresentable: UIView {
    let imageView = UIImageView()
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        configureView()
    }
    
    required init?(coder: NSCoder) {
        fatalError()
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        let imageConstraints = [
            imageView.widthAnchor.constraint(equalToConstant: bounds.width),
            imageView.heightAnchor.constraint(equalToConstant: bounds.height)
        ]
        
        NSLayoutConstraint.activate(imageConstraints)
    }
    
    private func configureView() {
        addSubview(imageView)
        imageView.translatesAutoresizingMaskIntoConstraints = false
    }
}
```

Usage:
```swift
// MARK: - GifImageView
struct GifImageView: View {
    var url: String
    
    var body: some View {
        ZStack {
            AnimatedGifView(
                url: Binding(get: { URL(string: url)! }, set: { _ in }),
                contentMode: .scaleAspectFit
            )
        }
    }
}
```
