### ISSUE TITLE
Keeps loading new gifs when scrolling in UITableView.

### ISSUE THREAD

**Issue by thijsheijden** [kirualex/SwiftyGif#77]
Hi, every time I scroll in the UITableView, it calls the cellForRowAt indexPath function, which in turn re-runs my code to download gifs. When not scrolling everything is fine, but as soon as I scroll it messes up and starts frantically loading new GIF's.

**Comment by alexiscreuzot** [comment]
If you call `setGifFromURL`, it is to be expected that downloads happens again, or at least data being loaded from cache again. I don't have a clear solution for this right now.
