### ISSUE TITLE
Bump podspec

### ISSUE THREAD

**Issue by pgawlowski** [kirualex/SwiftyGif#79]
After pod update still pointing to old version.

**Comment by alexiscreuzot** [comment]
did you do `pod repo update` first?

**Comment by diogoAntunes** [comment]
I have the same problem even after `pod repo update`

**Comment by hyouuu** [comment]
And if you look at the `releases` tab there's no new version after Feb :p

**Comment by pgawlowski** [comment]
@kirualex  - yup. Right now I manually pointed to github repo to solve this.

**Comment by dclelland** [comment]
Can confirm, running `pod repo update` then `pod update SwiftyGif` doesn't resolve this

**Comment by alexiscreuzot** [comment]
I pushed a new release on cocoapods, this should take care of this.
