### ISSUE TITLE
Not building at version 4.2

### ISSUE THREAD

**Issue by victormr** [kirualex/SwiftyGif#81]
Get this error: Type 'RunLoop' has no member 'Mode'.
At line 33 in SwiftyGifManager.

**Comment by KarthikSCP** [comment]
Even I was having the same problem. It seems there is something wrong with pods fetching the updated code. Need to figure out why. 
Mean time you can fix it by changing the code to 

`timer?.add(to: .main, forMode: .commonModes)`

**Comment by alexiscreuzot** [comment]
Could you try again, I think there was in issue with the tagging, it should be ok now

**Comment by victormr** [comment]
> Could you try again, I think there was in issue with the tagging, it should be ok now

It is exactly it. If i download by here https://github.com/kirualex/SwiftyGif/releases/tag/4.2.0 the problems still there :(.



> Even I was having the same problem. It seems there is something wrong with pods fetching the updated code. Need to figure out why.
> Mean time you can fix it by changing the code to
> 
> `timer?.add(to: .main, forMode: .commonModes)`

Thanks for the advice. I fixed the version anyway and will change from time to time.

**Comment by alexiscreuzot** [comment]
Testing here it does compile out of the box, so I gather it might come from a specific configuration on your side.

**Comment by Samback** [comment]
Have the same issue.

**Comment by alexiscreuzot** [comment]
please give details of your setup
