### ISSUE TITLE
Memory leak if set delegate 

### ISSUE THREAD

**Issue by korntom** [kirualex/SwiftyGif#84]
I heve animation view:
`        @IBOutlet weak var animationView: UIImageView!
`
And setup in viewDidLoad: 
```
        let gif = UIImage(gifName: data.animationName)
        animationView.delegate = delegate

        animationView.setGifImage(gif)
        animationView.loopCount = -1
        animationView.stopAnimatingGif()
```
I have memory leaks even with empty delegate implementation, even if I set weak self as delegate:
```
       weak var delegate = self
        animationView.delegate = delegate
```
When I comment line "animationView.delegate = self" there is no leaks.

**Comment by korntom** [comment]
I resolve this by resignation from the delegate and clear in deinit
```
    deinit {
        animationView?.clear()
    }
```

**Comment by Uniprog** [comment]
Assign association will resolve retain cycle:

            objc_setAssociatedObject(self, _delegateKey!, newValue, objc_AssociationPolicy.OBJC_ASSOCIATION_ASSIGN);

UIImageView+SwiftyGif.swift, line 438

**Comment by alexiscreuzot** [comment]
Should be fixed with https://github.com/kirualex/SwiftyGif/pull/97
