### ISSUE TITLE
updateImageView() method keeps calling even if i call clear() or stopAnimatingGif()

### ISSUE THREAD

**Issue by iBolom** [kirualex/SwiftyGif#89]
Hi,

I run Instruments and see that even if i called clear() or stopAnimatingGif() method that updateImageView() keeps calling...
I also tried to put imageView on nil but not helped.

I see in code that timer is added to run loop but never stopped.

Do you have idea how can i fix it because only on one screen i need to show gif and when user went from that screen i should stop it?

Thanks.

**Comment by alexiscreuzot** [comment]
Should be fixed with 77c38b69fefee9cb3af68acb7c7be1d6ef4195bb
