### ISSUE TITLE
Why Gif speed keep increasing on change image?

### ISSUE THREAD

**Issue by qasimsqm** [kirualex/SwiftyGif#90]
I am using to show a single UIImageView to show gif for different options but when i change its gif its speed is increased. Can I avoid this?
 let gifManager = SwiftyGifManager(memoryLimit:5)
        self.imgViewGif.isHidden = false
        switch menuArray[self.currentIndex] {
        case "burger":
            //show smoke
            self.imgViewGif.setGifImage(UIImage(), manager: gifManager)
            let gif = UIImage(gifName: "fire1.gif")//fileObject["file"]
            self.imgViewGif.setGifImage(gif, manager: gifManager)
            
            break
        case "pizza":
            //show fire
            self.imgViewGif.setGifImage(UIImage(), manager: gifManager)
            let gif = UIImage(gifName: "fire1.gif")//fileObject["file"]
            self.imgViewGif.setGifImage(gif, manager: gifManager)
            break
        case "smoothie":
            //show ice
           self.imgViewGif.setGifImage(UIImage(), manager: gifManager)
            let gif = UIImage(gifName: "ice.gif")
            self.imgViewGif.setGifImage(gif, manager: gifManager)
            break
        default: break
            //show smoke
        }

**Comment by yawaraym** [comment]
you must be creating `gifManager` multiple times. `SwiftyGifManager(memoryLimit:60)` this should be called only once.
