### ISSUE TITLE
XCode 10.2 Swift 5 Update

### ISSUE THREAD

**Issue by Rep0seNix** [kirualex/SwiftyGif#95]
@kirualex Could you update the project to the latest Swift 5 version? There are 36 minor warnings related to redundant 'public' modifier and deprecated 'index(of:)'.

**Comment by alexiscreuzot** [comment]
New 3.0.0 available on Cocoapods

**Comment by Rep0seNix** [comment]
@kirualex The latest was 4.2.0 Are we talking about different things?
